#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

with open('README.txt') as readme:
	long_description = readme.read()
with open('CHANGES.txt') as changes:
	long_description += '\n\n' + changes.read()

setup_params = dict(
	name='jaraco.mongodb',
	use_hg_version=True,
	author="Jason R. Coombs",
	author_email="jaraco@jaraco.com",
	description="jaraco.mongodb",
	long_description=long_description,
	url="https://bitbucket.org/jaraco/jaraco.mongodb",
	packages=setuptools.find_packages(),
	namespace_packages=['jaraco'],
	install_requires=[
		'pymongo',
		'python-dateutil',
	],
	setup_requires=[
		'hgtools',
		'pytest-runner',
	],
	tests_require=[
		'pytest',
		'jaraco.test>=1.5',
		'cherrypy',
	],
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
